### ISSUE TITLE
CUDA not found in docker image

### ISSUE THREAD

**Issue by mlong93** [zzzyuqing/DreamMat#14]
I pulled the official docker image but after installing all the dependencies, I'm getting torch.cuda.is_available() = False. 

Do you have further instructions to use the Docker image?

**Comment by XZYW7** [comment]
I encountered the same problem and the command `nvidia-smi` didn’t work in docker. I solved this by installing the NVIDIA Container Toolkit and adding the parameter `--gpus all` when running docker. If you haven’t installed it, you can refer to this [issue](https://github.com/NVIDIA/nvidia-docker/issues/1071), and the [installation guide](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
